spring:
  application:
    name: razzies-api
  datasource:
    url: jdbc:h2:mem:razziesdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  data:
    csv-path-movies-import: "classpath:data/movielist.csv"